### ISSUE TITLE
MinGW-w64-i686 builds fails with a1390ca

### ISSUE THREAD

**Issue by wiiaboo** [ultravideo/kvazaar#143]
```
$ ../configure --host=i686-w64-mingw32 --build=i686-w64-mingw32 --target=i686-w64-mingw32 --disable-shared --enable-static
$ make
[...]
../../src/strategies/avx2/picture-avx2.c: In function 'pixels_calc_ssd_avx2':
../../src/strategies/avx2/picture-avx2.c:650:11: error: unused variable 'temp' [-Werror=unused-variable]
   __m128i temp = _mm_setzero_si128();
           ^~~~
cc1.exe: all warnings being treated as errors
make[2]: *** [Makefile:1032: strategies/avx2/libavx2_la-picture-avx2.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/build/kvazaar-git/build-32bit/src'
make[1]: *** [Makefile:524: all-recursive] Error 1
make[1]: Leaving directory '/build/kvazaar-git/build-32bit'
make: *** [Makefile:394: all] Error 2
```

**Comment by Arizer** [comment]
Should be fixed in 29153ed
